// #include <string.h>
//
// #include "driver/gpio.h"
// #include "driver/i2c.h"
// #include "esp_err.h"
// #include "esp_log.h"
// #include "freertos/task.h"
//
// #include "sdkconfig.h" // generated by "make menuconfig"
//
// #include "ssd1366.h"
// #include "font8x8_basic.h"


#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"

#include "esp_log.h"
#include "esp_system.h"
#include "esp_err.h"

#include "driver/i2c.h"

#include "i2c.h"
#include "ssd1366.h"



static esp_err_t i2c_example_master_init()
{
    int i2c_master_port = I2C_MASTER_NUM;
    i2c_config_t conf;
    conf.mode = I2C_MODE_MASTER;
    conf.sda_io_num = I2C_MASTER_SDA_IO;
    conf.sda_pullup_en = 1;
    conf.scl_io_num = I2C_MASTER_SCL_IO;
    conf.scl_pullup_en = 1;
    conf.clk_stretch_tick = 30; // 300 ticks, Clock stretch is about 210us, you can make changes according to the actual situation.

		ESP_ERROR_CHECK(i2c_driver_install(i2c_master_port, conf.mode));
    ESP_ERROR_CHECK(i2c_param_config(i2c_master_port, &conf));
    return ESP_OK;
}

void task_ssd1306_display(void *pvParameter){

    int size = 10;
    pixel_color_t color = WHITE_PIXEL;

    while(1) {
      for (int i=0;i < 10; i++)
        ssd1306_draw_h_line(10, 30+i, size, color);

        ssd1306_display_data();

        size+=10;

        if (size > 100){
          size = 10;
            color ^= 1;
        }
        vTaskDelay(500 / portTICK_PERIOD_MS);
    }
}

void app_main(void)
{

	i2c_example_master_init();
  ssd1306_clearDisplay_buffer();

  /* Init display */
  ssd1306_init_new();
  ssd1306_display_clear();

  //for (i=0; i < 30; i++)
  // ssd1306_draw_pixel(0,0,WHITE_PIXEL);
  // ssd1306_draw_pixel(58,2,WHITE_PIXEL);
  // ssd1306_draw_pixel(58,58,WHITE_PIXEL);
  // ssd1306_draw_pixel(127,63,WHITE_PIXEL);

  //ssd1306_draw_line(4,25,90,WHITE_PIXEL);

  // for (i=0;i < 10; i++)
  //   ssd1306_draw_h_line(10, 30+i, 50, WHITE_PIXEL);

  // for (i=0; i < 30;i++)
  //     ESP_LOGI(tag, "%d = %d\n", i, oled_buffer[i]);

  //ssd1306_display_data();

  xTaskCreate(&task_ssd1306_display, "task_ssd1306_display", 2048, NULL, 5, NULL);

	//xTaskCreate(&task_ssd1306_display_pattern, "ssd1306_display_pattern",  2048, NULL, 6, NULL);
	//xTaskCreate(&task_ssd1306_display_clear, "ssd1306_display_clear",  2048, NULL, 6, NULL);
	//vTaskDelay(100/portTICK_PERIOD_MS);
  //xTaskCreate(&task_ssd1306_display_text, "ssd1306_display_text",  2048,
	// 	(void *)"Renan", 6, NULL);
	// xTaskCreate(&task_ssd1306_contrast, "ssid1306_contrast", 2048, NULL, 6, NULL);
	// xTaskCreate(&task_ssd1306_scroll, "ssid1306_scroll", 2048, NULL, 6, NULL);
}
